spring:
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE   #MySql Mode 사용 (import_schema_h2.sql에서 mysql 문법 그대로 사용 가능)
    username: sa
    password:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none      # 이미 정의된 테이블이니 auto generating from entity 대신 schema-locations을 사용한다.

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:sql/import_schema_h2.sql
      data-locations: classpath:sql/import_data_h2.sql
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
        trace: true
